require "#{File.dirname(__FILE__)}/constants.rb"
require "#{File.dirname(__FILE__)}/instances.rb"
require "#{File.dirname(__FILE__)}/pairs.rb"
require "#{File.dirname(__FILE__)}/txtio.rb"
require "#{File.dirname(__FILE__)}/motion_walking.rb"
require "#{File.dirname(__FILE__)}/motion_small.rb"
