require "#{File.dirname(__FILE__)}/annotation.rb"
require "#{File.dirname(__FILE__)}/ui_small_tools.rb"
require "#{File.dirname(__FILE__)}/ui_camera_tool.rb"
require "#{File.dirname(__FILE__)}/ui_setting_io.rb"
require "#{File.dirname(__FILE__)}/ui_target_tool.rb"